language: php

php:
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE accountbook;'

install:
  - composer install -n --dev --prefer-source
  - cp phpunit.xml.dist phpunit.xml
  - mysql -uroot accountbook < tests/data.sql

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)